apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.AppName }}-config
  namespace: {{ .Values.NameSpace }}
data:
  my.cnf: |
    [mysqld]
    sql_mode=''
    server-id = {{ .Values.MariadbServerId }}